In [ ]:
#Data Preprocessing

#Apply further data preprocessing according to the requirement. Count the number of missing values in each column and perform missing value treatment, if required.

In [1]:
import numpy as np
import pandas as pd

import warnings

# Ignore all warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_excel(r"C:\Users\91994\Downloads\DS1_C4_S9_Car_Data.xlsx")

In [3]:
missing_values = df.isnull().sum()
print(missing_values)

S. No.                               0
Make                                75
Model                                0
Variant                              0
Displacement                        12
Cylinders                           66
Valves_Per_Cylinder                102
Fuel_Tank_Capacity_litre            69
Fuel_Type                            0
Height_mm                            1
Length_mm                            0
Width_mm                            12
Body_Type                            6
Doors                                4
City_Mileage_km_litre              555
Highway_Mileage_km_litre           800
Kerb_Weight                        365
Power                                0
Torque                               2
Seating_Capacity                     6
Central_Locking                    149
Child_Safety_Locks                  75
Hill_Assist                        796
Drive_Modes                       1081
High_Speed_Alert_System           1068
ABS_(Anti-lock_Braking_System)     132
Gross_Vehicle_Weight               595
Airbags                            132
Door_Ajar_Warning                  143
Fasten_Seat_Belt_Warning           190
dtype: int64

In [4]:
df['Make'].value_counts()
df['Make'].mode()[0]
df['Make']=df['Make'].fillna('Not Available')
df['Make']

df['Displacement'].value_counts()
df['Displacement']=df['Displacement'].fillna(df['Displacement'].mean())
df['Displacement']

df['Cylinders'].value_counts()
df['Cylinders']=df['Cylinders'].fillna(df['Cylinders'].mean())
df['Cylinders']

df['Valves_Per_Cylinder'].value_counts()
df['Valves_Per_Cylinder']=df['Valves_Per_Cylinder'].fillna(df['Valves_Per_Cylinder'].mean())
df['Valves_Per_Cylinder']

df['Fuel_Tank_Capacity_litre'].value_counts()
df['Fuel_Tank_Capacity_litre']=df['Fuel_Tank_Capacity_litre'].fillna(df['Fuel_Tank_Capacity_litre'].mean())
df['Fuel_Tank_Capacity_litre']

df['Height_mm'].value_counts()
df['Height_mm']=df['Height_mm'].fillna(df['Height_mm'].mean())
df['Height_mm']

df['Width_mm'].value_counts()
df['Width_mm']=df['Width_mm'].fillna(df['Width_mm'].mean())
df['Width_mm']

df['Body_Type'].value_counts()
df['Body_Type']=df['Body_Type'].fillna("Not Availble")
df['Body_Type']

df['Doors'].value_counts()
df['Doors']=df['Doors'].fillna(df['Doors'].mean())
df['Doors']

df['City_Mileage_km_litre'].value_counts()
df['City_Mileage_km_litre']=df['City_Mileage_km_litre'].fillna(df['City_Mileage_km_litre'].mean())
df['City_Mileage_km_litre']

df['Highway_Mileage_km_litre'].value_counts()
df['Highway_Mileage_km_litre']=df['Highway_Mileage_km_litre'].fillna(df['Highway_Mileage_km_litre'].mean())
df['Highway_Mileage_km_litre']

df['Torque'].value_counts()
df['Torque']=df['Torque'].fillna(df['Torque'].mean())
df['Torque']

df['Seating_Capacity'].value_counts()
df['Seating_Capacity']=df['Seating_Capacity'].fillna(df['Seating_Capacity'].mean())
df['Seating_Capacity']

df['Central_Locking'].value_counts()
df['Central_Locking']=df['Central_Locking'].fillna("Not Available")
df['Central_Locking']

df['Child_Safety_Locks'].value_counts()
df['Child_Safety_Locks']=df['Child_Safety_Locks'].fillna("Not Available")
df['Child_Safety_Locks']

df['Hill_Assist'].value_counts()
df['Hill_Assist']=df['Hill_Assist'].fillna("Not Available")
df['Hill_Assist']

df['Drive_Modes'].value_counts()
df['Drive_Modes']=df['Drive_Modes'].fillna("Not Available")
df['Drive_Modes']

df['High_Speed_Alert_System'].value_counts()
df['High_Speed_Alert_System']=df['High_Speed_Alert_System'].fillna("Not Available")
df['High_Speed_Alert_System']

df['ABS_(Anti-lock_Braking_System)'].value_counts()
df['ABS_(Anti-lock_Braking_System)']=df['ABS_(Anti-lock_Braking_System)'].fillna("Not Available")
df['ABS_(Anti-lock_Braking_System)']

df['Airbags'].value_counts()
df['Airbags']=df['Airbags'].fillna("Not Available")
df['Airbags']

df['Door_Ajar_Warning'].value_counts()
df['Door_Ajar_Warning']=df['Door_Ajar_Warning'].fillna("Not Available")
df['Door_Ajar_Warning']


df['Fasten_Seat_Belt_Warning'].value_counts()
df['Fasten_Seat_Belt_Warning']=df['Fasten_Seat_Belt_Warning'].fillna("Not Available")
df['Fasten_Seat_Belt_Warning']

df['Gross_Vehicle_Weight'].value_counts()
df['Gross_Vehicle_Weight']=df['Gross_Vehicle_Weight'].fillna("Not Available")
df['Gross_Vehicle_Weight']

df['Kerb_Weight'].value_counts()
df['Kerb_Weight']=df['Kerb_Weight'].fillna("Not Available")
df['Kerb_Weight']

df.isnull().sum()

S. No.                            0
Make                              0
Model                             0
Variant                           0
Displacement                      0
Cylinders                         0
Valves_Per_Cylinder               0
Fuel_Tank_Capacity_litre          0
Fuel_Type                         0
Height_mm                         0
Length_mm                         0
Width_mm                          0
Body_Type                         0
Doors                             0
City_Mileage_km_litre             0
Highway_Mileage_km_litre          0
Kerb_Weight                       0
Power                             0
Torque                            0
Seating_Capacity                  0
Central_Locking                   0
Child_Safety_Locks                0
Hill_Assist                       0
Drive_Modes                       0
High_Speed_Alert_System           0
ABS_(Anti-lock_Braking_System)    0
Gross_Vehicle_Weight              0
Airbags                           0
Door_Ajar_Warning                 0
Fasten_Seat_Belt_Warning          0
dtype: int64

In [ ]:
#Task 1: Safety Feature Assessment

#Examine the presence of safety features such as ABS, airbags, and hill assist, to assess the safety standards of various car models with respect to each feature mentioned above.

In [ ]:
#Task 2: User Comfort Exploration

#Explore seating capacity, central locking, and child safety locks to understand user comfort and family-friendly features.

#Hint: Calculate the average seating capacity and count the occurrences of central locking and child safety locks for each model.

In [8]:
average_seating_capacity = df['Seating_Capacity'].mean()

# Count occurrences of central locking (assuming 1 for yes, 0 for no)
central_locking_count = df['Central_Locking'].value_counts()

# Count occurrences of child safety locks (assuming 1 for yes, 0 for no)
child_safety_locks_count = df['Child_Safety_Locks'].value_counts()

# Display results
display(f"Average Seating Capacity: {average_seating_capacity:.2f}")

# Display counts in a DataFrame format for better visualization
display(central_locking_count)
display(child_safety_locks_count)

'Average Seating Capacity: 5.27'

Central_Locking
Yes              1127
Not Available     149
Name: count, dtype: int64

Child_Safety_Locks
Yes              1201
Not Available      75
Name: count, dtype: int64

In [ ]:
#Task 3: Alert Systems Analysis

#Investigate the presence of high-speed alerts, seat belt reminders, and door-ajar warnings to assess the integration of safety and convenience features with respect to each feature mentioned above.

In [7]:
high_speed_alert_count = df['High_Speed_Alert_System'].value_counts()
seat_belt_reminder_count = df['Fasten_Seat_Belt_Warning'].value_counts()
door_ajar_warning_count = df['Door_Ajar_Warning'].value_counts()

# Display results
display("High-Speed Alert System Count:")
display(high_speed_alert_count)

display("Seat Belt Reminder Count:")
display(seat_belt_reminder_count)

display("Door Ajar Warning Count:")
display(door_ajar_warning_count)

'High-Speed Alert System Count:'

High_Speed_Alert_System
Not Available    1068
Yes               208
Name: count, dtype: int64

'Seat Belt Reminder Count:'

Fasten_Seat_Belt_Warning
Yes              1086
Not Available     190
Name: count, dtype: int64

'Door Ajar Warning Count:'

Door_Ajar_Warning
Yes              1133
Not Available     143
Name: count, dtype: int64

In [ ]:
#Task 4: Dimensional Analysis

#Analyze the dimensions of cars (height, length, width) to understand size preferences and market demands, aiding in product planning.

#Also, present make-wise average summaries for all dimensions of cars analyzed above

In [6]:
# Calculate make-wise average summaries for dimensions
average_dimensions = df.groupby('Make')[['Height_mm', 'Length_mm', 'Width_mm']].mean().reset_index()

# Rename the columns for better clarity
average_dimensions.columns = ['Make', 'Average Height (mm)', 'Average Length (mm)', 'Average Width (mm)']

# Display the results DataFrame
display(average_dimensions)

,Make,Average Height (mm),Average Length (mm),Average Width (mm)
0,Aston Martin,1294.333333,4623.000000,1982.333333
1,Audi,1544.759342,4715.096774,1876.437113
2,Bajaj,1652.000000,2752.000000,1312.000000
3,Bentley,1563.666667,5210.166667,2140.666667
4,Bmw,1541.486486,4816.891892,1980.243243
5,Bugatti,1212.000000,4544.000000,2038.000000
6,Datsun,1520.600000,3644.400000,1605.600000
7,Dc,1200.000000,4565.000000,2120.000000
8,Ferrari,1275.250000,4668.125000,1956.000000
9,Fiat,1517.739130,4195.086957,1708.565217
10,Force,2061.666667,4108.666667,1800.000000
11,Ford,1586.069767,4062.372093,1747.441860
12,Honda,1542.640625,4211.765625,1723.390625
13,Hyundai,1544.461538,4067.461538,1723.776923
14,Icml,1885.000000,4440.000000,1788.550506
15,Isuzu,1843.000000,5107.000000,1860.000000
16,Jaguar,1413.818182,4791.000000,1966.318182
17,Jeep,1669.535714,4475.107143,1838.357143
18,Kia,1671.190476,4505.476190,1844.047619
19,Lamborghini,1194.692308,4589.307692,1968.923077
20,Land Rover,1822.200000,4910.400000,2173.800000
21,Land Rover Rover,1782.370370,4875.407407,2137.037037
22,Lexus,1586.000000,4525.464000,1718.684000
23,Mahindra,1763.899160,4192.226891,1806.529412
24,Maruti Suzuki,1563.859060,3898.926174,1661.644295
25,Maruti Suzuki R,1671.071429,3655.000000,1623.928571
26,Maserati,1511.888889,4994.000000,2077.000000
27,Mg,1742.153846,4602.538462,1831.000000
28,Mini,1475.100000,4082.600000,1772.400000
29,Mitsubishi,1830.000000,4724.285714,1822.857143
30,Nissan,1583.068966,4264.000000,1753.482759
31,Not Available,1551.546667,4807.146667,1858.320000
32,Porsche,1509.000000,4793.500000,1950.000000
33,Premier,1730.000000,3970.000000,1570.000000
34,Renault,1612.833333,4121.361111,1717.000000
35,Skoda,1478.162791,4616.348837,1781.395349
36,Tata,1623.020000,4037.430000,1769.070000
37,Toyota,1601.829268,4385.621951,1761.158537
38,Volkswagen,1482.117647,4223.823529,1713.882353
39,Volvo,1597.500000,4667.277778,1994.611111